version: '3.8'

services:
  thor:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: thor
    container_name: thor
    user: thor              # run container as this user
    networks:
      - asgard
    command: sleep infinity
    volumes:
      - ./src:/home/thor/p2p-so1/src:ro

  loki:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: loki
    container_name: loki
    user: loki
    networks:
      - asgard
    command: sleep infinity
    volumes:
      - ./src:/home/loki/p2p-so1/src:ro

  odin:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: odin
    container_name: odin
    user: odin
    networks:
      - asgard
    command: sleep infinity
    volumes:
      - ./src:/home/odin/p2p-so1/src:ro

networks:
  asgard:
    driver: bridge
